// Generated by LiveScript 1.2.0
(function(){
  var BaseConfigLoader, FileConfigLoader, toString$ = {}.toString;
  BaseConfigLoader = require('./base-loader');
  module.exports = FileConfigLoader = (function(superclass){
    var prototype = extend$((import$(FileConfigLoader, superclass).displayName = 'FileConfigLoader', FileConfigLoader), superclass).prototype, constructor = FileConfigLoader;
    function FileConfigLoader(name, path, options){
      this.name = name;
      this.path = path;
      this.options = options != null
        ? options
        : {};
      FileConfigLoader.superclass.apply(this, arguments);
      this.validate();
      this;
    }
    prototype.validate = function(){
      if (toString$.call(this.path).slice(8, -1) !== 'String') {
        throw new Error("Path of config to load must be a String, was: " + this.path);
      }
    };
    prototype.hasConfig = function(name){
      name || (name = this.name);
      return this.exists(this.configFile(name));
    };
    prototype.loadConfig = function(name){
      return this.json(this.configFile(name));
    };
    prototype.configFile = function(name){
      name || (name = this.name);
      return [this.path, name + ".json"].join('/');
    };
    return FileConfigLoader;
  }(BaseConfigLoader));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
