// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    baseLoader: require('./base-loader'),
    compositeLoader: require('./composite-loader'),
    localLoader: require('./local-loader'),
    remoteLoader: require('./remote-loader')
  };
}).call(this);
