// Generated by LiveScript 1.2.0
(function(){
  var BaseLoader, Registry, RemoteConfigLoader;
  BaseLoader = require('./base-loader');
  Registry = require('../../registry');
  module.exports = RemoteConfigLoader = (function(superclass){
    var prototype = extend$((import$(RemoteConfigLoader, superclass).displayName = 'RemoteConfigLoader', RemoteConfigLoader), superclass).prototype, constructor = RemoteConfigLoader;
    function RemoteConfigLoader(name, registry){
      this.name = name;
      RemoteConfigLoader.superclass.apply(this, arguments);
      if (registry) {
        this._registry = registry;
      }
    }
    prototype.loadConfig = function(){
      throw Error("Not implemented, insteas install into Local registry");
    };
    prototype.configFile = function(name){
      name || (name = this.name);
      return this.registry().readConfig(name);
    };
    prototype.hasConfig = function(name){
      name || (name = this.name);
      return this.registry().has(name);
    };
    prototype.install = function(name){
      name || (name = this.name);
      return this.registry().install(name);
    };
    prototype.registry = function(){
      return this._registry || (this._registry = new Registry('uri'));
    };
    return RemoteConfigLoader;
  }(BaseLoader));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
