// Generated by LiveScript 1.2.0
(function(){
  var FileIO, Adder, toString$ = {}.toString;
  FileIO = require('./file-io');
  Adder = {
    addLibs: function(key, names){
      var obj, i$, ref$, len$, k;
      if (toString$.call(key).slice(8, -1) === 'Object' && Object.keys(key).length > 0) {
        obj = key;
        for (i$ = 0, len$ = (ref$ = Object.keys(obj)).length; i$ < len$; ++i$) {
          k = ref$[i$];
          this.addLibs(k, obj[k]);
        }
        return this;
      }
      this.init(key);
      if (typeof names === 'string') {
        names = [names];
      }
      if (toString$.call(names).slice(8, -1) !== 'Array') {
        throw new Error("lib(s) to add must be a String or Array");
      }
      if (!(names.length > 0)) {
        return;
      }
      this.libs[key].libs = (this.libs[key].libs || []).concat(names);
      return this;
    },
    addRemaps: function(key, obj){
      var ref$, name, value;
      obj == null && (obj = {});
      this.init(key);
      if (toString$.call(obj).slice(8, -1) !== 'Object') {
        throw new Error("Remap must be an Object");
      }
      if (!(Object.keys(obj).length > 0)) {
        return;
      }
      (ref$ = this.libs[key]).remap || (ref$.remap = {});
      for (name in obj) {
        value = obj[name];
        this.addRemap(key, name, value);
      }
      return this;
    },
    addRemap: function(key, name, value){
      this.libs[key].remap[name] = value;
      return this;
    }
  };
  import$(Adder, FileIO);
  module.exports = Adder;
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
