// Generated by LiveScript 1.2.0
(function(){
  var fs, config, Composite, Directory, Importer;
  fs = require('fs');
  config = {};
  Composite = require('./composite');
  Directory = (function(){
    Directory.displayName = 'Directory';
    var prototype = Directory.prototype, constructor = Directory;
    function Directory(app, config){
      this.app = app;
      this.config = config;
    }
    prototype.bowerDir = function(){
      if (this.name === 'bower') {
        return this.app.bowerDirectory;
      }
    };
    prototype.dir = function(name){
      this.name = name;
      return this.config[this.name] || this.bowerDir() || this.name;
    };
    return Directory;
  }());
  module.exports = Importer = (function(){
    Importer.displayName = 'Importer';
    var prototype = Importer.prototype, constructor = Importer;
    function Importer(app, options){
      this.app = app;
      this.options = options != null
        ? options
        : {};
      this.file = this.options.file || './imports/libraries.json';
      this.libs();
      this;
    }
    prototype.readLibs = function(){
      return fs.readFileSync(this.file, 'utf8');
    };
    prototype.libs = function(){
      return this.libs = JSON.parse(this.readLibs());
    };
    prototype.dir = function(name){
      return this.directory().dir(name);
    };
    prototype.directory = function(){
      return this._directory || (this._directory = new Directory(this.app, this.config));
    };
    prototype.importAll = function(){
      var key, ref$, value, results$ = [];
      this.config = this.options.config || this.libs['config'] || {};
      delete this.libs['config'];
      for (key in ref$ = this.libs) {
        value = ref$[key];
        results$.push(this.importFor(key, value));
      }
      return results$;
    };
    prototype.importFor = function(name, values){
      return new Composite(this.app, this.dir(name)).importAll(values);
    };
    return Importer;
  }());
}).call(this);
