// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    libraries: require('./lib/libraries'),
    dummyApp: function(io){
      io || (io = console.log);
      return {
        'import': function(location, opts){
          var x;
          opts == null && (opts = '');
          x = opts ? '", ' : '"';
          return io('app.import(  "' + location + x, opts, ');');
        },
        bowerDirectory: 'bower_components'
      };
    }
  };
}).call(this);
