// Generated by LiveScript 1.2.0
(function(){
  var Importer, Adder, importAll;
  Importer = require('./importer');
  Adder = require('./adder');
  importAll = function(app, options){
    options == null && (options = {});
    return new Importer(app, options).importAll();
  };
  module.exports = {
    importAll: importAll,
    adder: new Adder
  };
}).call(this);
