// Generated by LiveScript 1.2.0
(function(){
  var Importer, importAll;
  Importer = require('./importer');
  importAll = function(app, file){
    return new Importer(app, file).importAll();
  };
  module.exports = {
    importAll: importAll
  };
}).call(this);
