// Generated by LiveScript 1.2.0
(function(){
  var fs;
  fs = require('fs');
  module.exports = {
    readLibs: function(){
      return fs.readFileSync(this.file, 'utf8');
    },
    libs: function(){
      return this.libs = JSON.parse(this.readLibs());
    }
  };
}).call(this);
