// Generated by LiveScript 1.2.0
(function(){
  var FileIO, Remover, toString$ = {}.toString;
  FileIO = require('./file-io');
  Remover = {
    removeLibs: function(key, names){
      var obj, i$, ref$, len$, k, name;
      if (toString$.call(key).slice(8, -1) === 'Object' && Object.keys(key).length > 0) {
        obj = key;
        for (i$ = 0, len$ = (ref$ = Object.keys(obj)).length; i$ < len$; ++i$) {
          k = ref$[i$];
          this.removeLibs(k, obj[k]);
        }
        return this;
      }
      this.init(key);
      if (typeof names === 'string') {
        names = [names];
      }
      if (toString$.call(names).slice(8, -1) !== 'Array') {
        throw new Error("lib(s) to remove must be a String or Array");
      }
      if (!(names.length > 0)) {
        return;
      }
      for (i$ = 0, len$ = names.length; i$ < len$; ++i$) {
        name = names[i$];
        this.removeLib(key, name);
      }
      return this;
    },
    removeLib: function(key, name){
      var index;
      if (toString$.call(name).slice(8, -1) !== 'String') {
        throw new Error("lib to remove must be a String");
      }
      index = this.libs[key].libs.indexOf(name);
      if (index > -1) {
        this.libs[key].libs.splice(index, 1);
      }
      return this;
    },
    removeRemaps: function(key, mapNames){
      var ref$, i$, len$, mapName;
      this.init(key);
      if (typeof mapNames === 'string') {
        mapNames = [mapNames];
      }
      if (toString$.call(mapNames).slice(8, -1) !== 'Array') {
        throw new Error("Map names to remove must be an Array or String");
      }
      if (!(mapNames.length > 0)) {
        return;
      }
      (ref$ = this.libs[key]).remap || (ref$.remap = {});
      for (i$ = 0, len$ = mapNames.length; i$ < len$; ++i$) {
        mapName = mapNames[i$];
        this.removeRemap(key, mapName);
      }
      return this;
    },
    removeRemap: function(key, mapName){
      if (this.libs[key].remap[mapName]) {
        delete this.libs[key].remap[mapName];
      }
      return this;
    }
  };
  import$(Remover, FileIO);
  module.exports = Remover;
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
