// Generated by LiveScript 1.2.0
/**
 * User: kristianmandrup
 * Date: 06/10/14
 * Time: 14:40
 */
(function(){
  var Component, ListMutator, Components, toString$ = {}.toString;
  Component = require('./component');
  ListMutator = require('../list-mutator');
  module.exports = Components = (function(){
    Components.displayName = 'Components';
    var prototype = Components.prototype, constructor = Components;
    importAll$(prototype, arguments[0]);
    function Components(list){
      this.list = list;
    }
    prototype.validate = function(){
      if (toString$.call(this.libs).slice(8, -1) !== 'Array') {
        throw new Error("Must be an Array");
      }
    };
    prototype.component = function(name){
      return new Component(name);
    };
    prototype.addOne = function(name){
      this.list.push(name);
      return this;
    };
    prototype.removeOne = function(name){
      this._removeItem(this.list, name);
      return this;
    };
    prototype.index = function(name){
      return this.list.indexOf(name);
    };
    return Components;
  }(ListMutator));
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
