// Generated by LiveScript 1.2.0
/**
 * User: kristianmandrup
 * Date: 06/10/14
 * Time: 14:40
 */
(function(){
  var Component, Components;
  Component = require('./component');
  module.exports = Components = (function(){
    Components.displayName = 'Components';
    var prototype = Components.prototype, constructor = Components;
    function Components(configurator){
      this.configurator = configurator;
    }
    prototype.component = function(){
      return new Component;
    };
    prototype.add = function(name){};
    prototype.remove = function(name){};
    return Components;
  }());
}).call(this);
