// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    componentConfig: require('./component-config'),
    component: require('./component'),
    components: require('./components')
  };
}).call(this);
