// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    baseAdapter: require('./base-adapter'),
    basicAdapter: require('./basic-adapter'),
    localAdapter: require('./local-adapter'),
    remoteAdapter: require('./remote-adapter')
  };
}).call(this);
