// Generated by LiveScript 1.2.0
(function(){
  var FileAdapter, PkgAdapter, LocalRegistryAdapter, toString$ = {}.toString;
  FileAdapter = require('./local/file-adapter');
  PkgAdapter = require('./local/pkg-adapter');
  module.exports = LocalRegistryAdapter = (function(){
    LocalRegistryAdapter.displayName = 'LocalRegistryAdapter';
    var prototype = LocalRegistryAdapter.prototype, constructor = LocalRegistryAdapter;
    function LocalRegistryAdapter(options){
      this.options = options != null
        ? options
        : {};
      this.type || (this.type = this.options.type || 'bower');
      this.installerType = this.options.installer || 'json';
      this.adapterType = this.options.adapter || 'pkg';
      LocalRegistryAdapter.superclass.apply(this, arguments);
      this.validate();
      this;
    }
    prototype.validate = function(){
      if (toString$.call(this.type).slice(8, -1) !== 'String') {
        throw Error("Type must be a String, was: " + this.type);
      }
      if (toString$.call(this.adapterType).slice(8, -1) !== 'String') {
        throw Error("adapter type must be a String, was: " + this.adapterType);
      }
    };
    prototype.load = function(){
      return this.adapter().load();
    };
    prototype.install = function(){
      return this.adapter().install(this.installerType);
    };
    prototype.adapter = function(){
      var clazz;
      clazz = this.selectedAdapter();
      return new clazz(this.options);
    };
    prototype.selectedAdapter = function(){
      return this.adapter[this.adapterType] || this.badAdapter();
    };
    prototype.adapters = {
      file: FileAdapter,
      pkg: PkgAdapter
    };
    prototype.badAdapter = function(){
      throw new Error("unknown adapter " + this.adapterType);
    };
    return LocalRegistryAdapter;
  }());
}).call(this);
