// Generated by LiveScript 1.2.0
(function(){
  var UriAdapter, BasicRegistryAdapter, RemoteRegistryAdapter;
  UriAdapter = require('./remote/uri-adapter');
  BasicRegistryAdapter = require('./basic-adapter');
  module.exports = RemoteRegistryAdapter = (function(superclass){
    var prototype = extend$((import$(RemoteRegistryAdapter, superclass).displayName = 'RemoteRegistryAdapter', RemoteRegistryAdapter), superclass).prototype, constructor = RemoteRegistryAdapter;
    function RemoteRegistryAdapter(options){
      this.options = options != null
        ? options
        : {};
      RemoteRegistryAdapter.superclass.apply(this, arguments);
    }
    prototype.adapters = {
      uri: UriAdapter
    };
    return RemoteRegistryAdapter;
  }(BasicRegistryAdapter));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
