// Generated by LiveScript 1.2.0
(function(){
  var FileIO, Installer, BaseAdapter, fs, syncRequest, Github, RegistryUriAdapter, toString$ = {}.toString;
  FileIO = require('../../file-io');
  Installer = require('../installer');
  BaseAdapter = require('./base-adapter');
  fs = require('fs-extra');
  syncRequest = require('sync-request');
  Github = require('./repo/github');
  module.exports = RegistryUriAdapter = (function(superclass){
    var prototype = extend$((import$(RegistryUriAdapter, superclass).displayName = 'RegistryUriAdapter', RegistryUriAdapter), superclass).prototype, constructor = RegistryUriAdapter;
    importAll$(prototype, arguments[1]);
    function RegistryUriAdapter(options){
      this.options = options != null
        ? options
        : {};
      this.registryUri = this.options.registryUri || this.defaultUri();
      this.type || (this.type = 'bower');
      RegistryUriAdapter.superclass.apply(this, arguments);
    }
    prototype.defaultUri = function(){
      return this.defaultRepo().registryPath(this.options.repo);
    };
    prototype.defaultRepo = function(){
      return new Github;
    };
    prototype.validate = function(){
      if (toString$.call(this.registryUri).slice(8, -1) !== 'String') {
        throw new Error("registryUri must be a String, was:");
      }
      if (toString$.call(this.localRegistryPath).slice(8, -1) !== 'String') {
        throw new Error("localRegistryPath must be a String, was " + this.localRegistryPath);
      }
    };
    prototype.installer = function(){
      return this._installer || (this._installer = new Installer);
    };
    prototype.install = function(name){
      return this.installer.install({
        source: this.readConfig(name),
        target: this.targetConfig(name)
      });
    };
    prototype.readConfig = function(name){
      return this.index()[name];
    };
    prototype.registryLibsUri = function(){
      return [this.registryUri, this.libsFile()].join('/');
    };
    prototype.libsFile = function(){
      return this.type + "-libs.json";
    };
    prototype.indexContent = function(options){
      options == null && (options = {});
      return this._indexContent || (this._indexContent = this.retrieve());
    };
    prototype.retrieve = function(){
      return syncRequest('GET', this.registryLibsUri()).getBody();
    };
    prototype.index = function(){
      return JSON.parse(this.indexContent());
    };
    prototype.list = function(){
      return this._list || (this._list = Object.keys(this.index()));
    };
    return RegistryUriAdapter;
  }(BaseAdapter, FileIO));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
