// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    baseInstaller: require('./base-installer'),
    fileInstaller: require('./file-installer'),
    jsonInstaller: require('./json-installer')
  };
}).call(this);
