// Generated by LiveScript 1.2.0
(function(){
  var fs, FileIO;
  fs = require('fs-extra');
  FileIO = require('./file-io');
  module.exports = {
    read: function(file){
      file || (file = this.file);
      return this.content || (this.content = fs.readFileSync(file, 'utf8'));
    },
    save: function(file){
      file || (file = this.file);
      return this.writeFile(file, this.string(file));
    },
    writeFile: function(file, content){
      file || (file = this.file);
      this.createPath(file);
      return fs.writeFileSync(file, content);
    },
    createPath: function(file){
      var path;
      file || (file = this.file);
      path = require('path').dirname(file);
      return fs.mkdirp(path);
    },
    saveContent: function(file, content){
      file || (file = this.file);
      content || (content = this.content);
      this.writeFile(content);
      return this;
    },
    string: function(file){
      file || (file = this.file);
      return JSON.stringify(this.json(file), null, '  ');
    },
    exists: function(file){
      file || (file = this.file);
      return fs.existsSync(file);
    },
    load: function(file){
      file || (file = this.file);
      this._json = void 8;
      this.json(file);
      return this;
    },
    json: function(file){
      file || (file = this.file);
      return this._json || (this._json = JSON.parse(this.read(file)));
    },
    print: function(io){
      io == null && (io = console.log);
      io(this.json());
      return this;
    }
  };
}).call(this);
