// Generated by LiveScript 1.2.0
(function(){
  var fs, FileIO;
  fs = require('fs');
  FileIO = require('./file-io');
  module.exports = {
    read: function(file){
      this.file = file;
      return this.content || (this.content = fs.readFileSync(this.file, 'utf8'));
    },
    save: function(file){
      file || (file = this.file);
      fs.writeFileSync(file, this.string());
      return this;
    },
    string: function(){
      return JSON.stringify(this.json(), null, '  ');
    },
    exists: function(){
      return fs.existsSync(this.file);
    },
    load: function(file){
      file || (file = this.file);
      this._json = void 8;
      this.json(file);
      return this;
    },
    json: function(file){
      file || (file = this.file);
      return this._json || (this._json = JSON.parse(this.read(file)));
    },
    print: function(io){
      io == null && (io = console.log);
      io(this.json());
      return this;
    }
  };
}).call(this);
