// Generated by LiveScript 1.2.0
(function(){
  var FileIO, fs, jsonlint, GlobalConfig, toString$ = {}.toString;
  FileIO = require('./util/file-io');
  fs = require('fs-extra');
  jsonlint = require('jsonlint');
  module.exports = GlobalConfig = (function(){
    GlobalConfig.displayName = 'GlobalConfig';
    var prototype = GlobalConfig.prototype, constructor = GlobalConfig;
    importAll$(prototype, arguments[0]);
    function GlobalConfig(options){
      this.options = options;
      this.librariesrc = './.librariesrc';
      this;
    }
    prototype.rcJson = function(){
      return this._rcJson || (this._rcJson = jsonlint.parse(this.loadRc()));
    };
    prototype.defaultLocationOf = function(paths){
      return this.locationOf(paths, this['default'](), true);
    };
    prototype.locationOf = function(paths, obj, d){
      var path, val, dir;
      if (toString$.call(paths).slice(8, -1) === 'String') {
        paths = paths.split('.');
      }
      path = paths.shift();
      val = obj[path];
      if (toString$.call(val).slice(8, -1) === 'Function') {
        val = val();
      }
      if (d && path !== 'dir') {
        dir = obj.dir;
        if (toString$.call(dir).slice(8, -1) === 'Function') {
          dir = dir();
        }
        if (toString$.call(val).slice(8, -1) !== 'String') {
          val = path;
        }
        if (toString$.call(dir).slice(8, -1) === 'String') {
          val = [dir, val].join('/');
        }
      }
      if (paths.length === 0 || toString$.call(val).slice(8, -1) === 'String') {
        return val;
      }
      return this.locationOf(paths, val, true);
    };
    prototype.findLocationOf = function(path, obj){
      return this.locationOf(path, this.rcJson()) || this.defaultLocationOf(path);
    };
    prototype.location = function(path){
      var loc;
      loc = [this.rcJson().dir];
      path = this.findLocationOf(path, this.rcJson());
      loc = loc.concat(path);
      return loc = loc.join('/');
    };
    prototype.loadRc = function(){
      return this.read(this.librariesrc);
    };
    prototype.select = function(){
      var this$ = this;
      return {
        file: function(){
          return this$.location('select.file');
        }
      };
    };
    prototype.builds = function(){
      var this$ = this;
      return {
        dir: function(){
          return this$.location('builds.dir');
        }
      };
    };
    prototype.components = function(){
      var this$ = this;
      return {
        dir: function(){
          return this$.location('components.dir');
        },
        file: function(){
          return this$.location('components.file');
        }
      };
    };
    prototype.config = function(){
      var this$ = this;
      return {
        file: function(){
          return this$.location('config.file');
        }
      };
    };
    prototype.registries = function(){
      return this.parseRegistries(this.location('registries'));
    };
    prototype.parseRegistries = function(regs){
      return regs;
    };
    prototype['default'] = function(){
      return {
        dir: './xlibs',
        builds: function(){
          var this$ = this;
          return {
            dir: function(){
              return [this$.dir, 'builds'].join('/');
            }
          };
        },
        components: function(){
          var this$ = this;
          return {
            dir: function(){
              return [this$.dir, 'components'].join('/');
            },
            file: function(){
              return [this.dir, 'index.json'].join('/');
            }
          };
        },
        select: function(){
          var this$ = this;
          return {
            file: function(){
              return [this$.dir, 'select'].join('/');
            }
          };
        },
        config: function(){
          var this$ = this;
          return {
            file: function(){
              return [this$.dir, 'config.json'].join('/');
            }
          };
        },
        registries: [{
          name: 'libraries-official',
          type: 'uri',
          repo: 'kristianmandrup/libraries'
        }]
      };
    };
    return GlobalConfig;
  }(FileIO));
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
