// Generated by LiveScript 1.2.0
(function(){
  var Selector, Configurator, Registry, Generator;
  Selector = require('./select/selector');
  Configurator = require('./config/configurator');
  Registry = require('./registry/registry');
  Generator = require('./output/generator');
  module.exports = {
    select: new Selector,
    config: new Configurator,
    registry: new Registry,
    build: function(){
      var i$, ref$, len$, lib, results$ = [];
      console.log('building...', this.config);
      for (i$ = 0, len$ = (ref$ = this.select.list()).length; i$ < len$; ++i$) {
        lib = ref$[i$];
        results$.push(this.config);
      }
      return results$;
    }
  };
}).call(this);
