// Generated by LiveScript 1.2.0
/**
 * User: kristianmandrup
 * Date: 07/10/14
 * Time: 23:07
 */
(function(){
  var toString$ = {}.toString;
  module.exports = {
    add: function(names){
      var i$, len$, name;
      names = this._normalize(names);
      for (i$ = 0, len$ = names.length; i$ < len$; ++i$) {
        name = names[i$];
        this.addOne(name);
      }
      return this;
    },
    remove: function(names){
      var i$, len$, name;
      names = this._normalize(names);
      for (i$ = 0, len$ = names.length; i$ < len$; ++i$) {
        name = names[i$];
        this.removeOne(name);
      }
      return this;
    },
    _normalize: function(names){
      if (toString$.call(names).slice(8, -1) === 'String') {
        return [names];
      } else {
        return names;
      }
    },
    _removeItem: function(list, name){
      if (!this.has(name)) {
        return this;
      }
      return list.splice(this.index(name), 1);
    },
    has: function(name){
      return this.index(name) > -1;
    }
  };
}).call(this);
