// Generated by LiveScript 1.2.0
(function(){
  var expect, Github, log;
  expect = require('chai').expect;
  Github = require('../../../../../lib/registry/adapter/repo/github');
  log = console.log;
  describe('Github repo adapter', function(){
    var github;
    return describe('valid instance', function(){
      before(function(){
        return github = new Github;
      });
      return describe('registry-path', function(){
        return specify('is github path', function(){
          return expect(github.registryPath()).to.eql("https://raw.githubusercontent.com/kristianmandrup/libraries/master/registry");
        });
      });
    });
  });
}).call(this);
