// Generated by LiveScript 1.2.0
(function(){
  var Github;
  module.exports = Github = (function(){
    Github.displayName = 'Github';
    var prototype = Github.prototype, constructor = Github;
    function Github(){
      this.host = 'https://raw.githubusercontent.com';
      this.branch = 'master';
      this.folder = 'registry';
      this;
    }
    prototype.registryPath = function(repo){
      repo == null && (repo = 'kristianmandrup/libraries');
      return [this.host, repo, this.branch, this.folder].join('/');
    };
    return Github;
  }());
}).call(this);
