// Generated by LiveScript 1.2.0
(function(){
  var fs, jsonlint, FileIO;
  fs = require('fs-extra');
  jsonlint = require('jsonlint');
  FileIO = require('./file-io');
  module.exports = {
    read: function(file){
      file || (file = this.file);
      return this.content || (this.content = fs.readFileSync(file, 'utf8'));
    },
    save: function(file){
      file || (file = this.file);
      return this.writeFile(file, this.string(file));
    },
    writeFile: function(file, content){
      file || (file = this.file);
      content || (content = this.content);
      this.createPath(file);
      return fs.writeFileSync(file, content, 'utf8');
    },
    removeFile: function(file){
      file || (file = this.file);
      return fs.unlinkSync(file);
    },
    createPath: function(file){
      var path;
      file || (file = this.file);
      path = require('path').dirname(file);
      return fs.mkdirp(path);
    },
    saveContent: function(file, content){
      file || (file = this.file);
      content || (content = this.content);
      this.writeFile(content);
      return this;
    },
    string: function(file){
      file || (file = this.file);
      return JSON.stringify(this.json(file), null, '  ');
    },
    exists: function(file){
      file || (file = this.file);
      return fs.existsSync(file);
    },
    load: function(file){
      file || (file = this.file);
      this._json = void 8;
      this.json(file);
      return this;
    },
    json: function(file){
      file || (file = this.file);
      return this._json || (this._json = JSON.parse(this.read(file)));
    },
    jsonlint: function(content){
      content || (content = this.content);
      return this._jsonlint || (this._jsonlint = jsonlint.parse(content));
    },
    print: function(io){
      io == null && (io = console.log);
      io(this.json());
      return this;
    },
    error: function(msg){
      return console.error(msg);
    }
  };
}).call(this);
