// Generated by LiveScript 1.2.0
(function(){
  var Container;
  module.exports = Container = (function(){
    Container.displayName = 'Container';
    var prototype = Container.prototype, constructor = Container;
    function Container(obj){
      this.obj = obj;
    }
    prototype.components = function(){
      return this._components || (this._components = this.obj.components || []);
    };
    prototype.libs = function(){
      return this._libs || (this._libs = this.obj.libs || {});
    };
    prototype.libsList = function(){
      return this._libsList || (this._libsList = Object.keys(this.libs()));
    };
    prototype.isComponent = function(name){
      return this.components().indexOf(name) > -1;
    };
    prototype.isLib = function(name){
      return this.libsList().indexOf(name) > -1;
    };
    prototype.has = function(name){
      return this.isComponent(name) || this.isLib(name);
    };
    return Container;
  }());
}).call(this);
