// Generated by LiveScript 1.2.0
(function(){
  var Container, util, Containers, toString$ = {}.toString;
  Container = require('./container');
  util = require('util');
  module.exports = Containers = (function(){
    Containers.displayName = 'Containers';
    var prototype = Containers.prototype, constructor = Containers;
    function Containers(containerObjs, config){
      this.containerObjs = containerObjs;
      this.config = config;
      this.validate();
      this;
    }
    prototype.validate = function(){
      if (toString$.call(this.containerObjs).slice(8, -1) !== 'Object') {
        throw new Error("Container objects must be an Object, was: " + util.inspect(this.containerObjs));
      }
      if (toString$.call(this.config).slice(8, -1) !== 'Object') {
        throw new Error("Config must be an Object, was: " + util.inspect(this.config));
      }
    };
    prototype.all = function(){
      var this$ = this;
      return this._all || (this._all = Object.keys(this.containerObjs).map(function(name){
        return this$.container(name);
      }));
    };
    prototype.container = function(name){
      return new Container(this.containerObjs[name] || {}, this.config);
    };
    prototype.build = function(){
      this.install();
      return this.all().map(function(container){
        return container.build();
      });
    };
    prototype.install = function(){
      return this.all().map(function(container){
        return container.install();
      });
    };
    return Containers;
  }());
}).call(this);
