// Generated by LiveScript 1.2.0
/**
 * User: kristianmandrup
 * Date: 11/10/14
 * Time: 09:47
 */
(function(){
  var Container, Containers;
  Container = require('./container');
  module.exports = Containers = (function(){
    Containers.displayName = 'Containers';
    var prototype = Containers.prototype, constructor = Containers;
    function Containers(containerObjs, config){
      this.containerObjs = containerObjs;
      this.config = config;
    }
    prototype.containers = function(){
      var this$ = this;
      return this._containers || (this._containers = Object.keys(this.containerObjs).map(function(name){
        return this$.container(name);
      }));
    };
    prototype.container = function(name){
      return new Container(this.containerObjs[name] || {}, this.config);
    };
    prototype.build = function(){
      return this._build || (this._build = this.containers().map(function(container){
        return container.build();
      }));
    };
    return Containers;
  }());
}).call(this);
