// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    compositeRegistry: require('./composite-registry'),
    configLoader: require('./config-loader'),
    registry: require('./registry')
  };
}).call(this);
