// Generated by LiveScript 1.2.0
(function(){
  var FileInstaller, JsonInstaller, Installer, slice$ = [].slice, toString$ = {}.toString;
  FileInstaller = require('./installer/file-installer');
  JsonInstaller = require('./installer/json-installer');
  module.exports = Installer = (function(){
    Installer.displayName = 'Installer';
    var prototype = Installer.prototype, constructor = Installer;
    function Installer(type){
      this.type = type;
      this.args = slice$.call(arguments, 1);
      this.type || (this.type = 'file');
      this.validate();
    }
    prototype.validate = function(){
      if (toString$.call(this.type).slice(8, -1) !== 'String') {
        throw new Error("Type must be a String, was: " + this.type);
      }
    };
    prototype.adapter = function(){
      return new this.selectedInstaller().apply(null, this.args);
    };
    prototype.selectAdapter = function(){
      switch (this.type) {
      case 'file':
        return FileInstaller;
      case 'json':
        return JsonInstaller;
      default:
        throw new Error("unknown Installer " + this.type);
      }
    };
    return Installer;
  }());
}).call(this);
