// Generated by LiveScript 1.2.0
/**
 * User: kristianmandrup
 * Date: 12/10/14
 * Time: 12:37
 */
(function(){
  var FileIO, BaseConfigLoader, toString$ = {}.toString;
  FileIO = require('../../file-io');
  module.exports = BaseConfigLoader = (function(){
    BaseConfigLoader.displayName = 'BaseConfigLoader';
    var prototype = BaseConfigLoader.prototype, constructor = BaseConfigLoader;
    importAll$(prototype, arguments[0]);
    function BaseConfigLoader(name, path){
      this.name = name;
      this.path = path;
      this.path || (this.path = './xlibs/components');
      this.validate();
      this;
    }
    prototype.validate = function(){
      if (toString$.call(this.name).slice(8, -1) !== 'String') {
        throw new Error("Name of config to load must be a String, was: " + this.name);
      }
    };
    prototype.loadConfig = function(){
      if (this.hasConfig()) {
        return this.load(this.configFile());
      }
    };
    prototype.load = function(filePath){
      var err;
      try {
        return this.json(filePath);
      } catch (e$) {
        err = e$;
        return this.error(err);
      }
    };
    prototype.error = function(msg){
      return console.error(msg);
    };
    return BaseConfigLoader;
  }(FileIO));
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
