// Generated by LiveScript 1.2.0
/**
 * User: kristianmandrup
 * Date: 12/10/14
 * Time: 12:30
 */
(function(){
  var BaseConfigLoader, LocalConfigLoader, toString$ = {}.toString;
  BaseConfigLoader = require('./base');
  module.exports = LocalConfigLoader = (function(superclass){
    var prototype = extend$((import$(LocalConfigLoader, superclass).displayName = 'LocalConfigLoader', LocalConfigLoader), superclass).prototype, constructor = LocalConfigLoader;
    function LocalConfigLoader(name, path){
      this.name = name;
      this.path = path;
      LocalConfigLoader.superclass.apply(this, arguments);
      this.validate();
      this;
    }
    prototype.validate = function(){
      if (toString$.call(this.path).slice(8, -1) !== 'String') {
        throw new Error("Path of config to load must be a String, was: " + this.path);
      }
    };
    prototype.hasConfig = function(name){
      name || (name = this.name);
      return this.exists(this.configFile(name));
    };
    prototype.configFile = function(name){
      name || (name = this.name);
      return [this.path, name + ".json"].join('/');
    };
    return LocalConfigLoader;
  }(BaseConfigLoader));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
