// Generated by LiveScript 1.2.0
(function(){
  var expect, Component;
  expect = require('chai').expect;
  Component = require('../../../lib/component/component');
  describe('Adder', function(){
    var component, comp, conf;
    conf = {};
    conf.bootstrap = {
      dir: 'dist',
      scripts: {
        files: ['js/bootstrap.js']
      }
    };
    describe('create', function(){
      context('invalid', function(){
        specify('no args throws', function(){
          return expect(function(){
            return new Component;
          }).to['throw'];
        });
        specify('bad nam throws', function(){
          return expect(function(){
            return new Component(7);
          }).to['throw'];
        });
        return specify('no obj throws', function(){
          return expect(function(){
            return new Component('x');
          }).to['throw'];
        });
      });
      return context('valid', function(){
        return specify('name and obj :)', function(){
          return expect(function(){
            return new Component('x', {});
          }).to.not['throw'];
        });
      });
    });
    return describe('valid component', function(){});
  });
}).call(this);
