// Generated by LiveScript 1.2.0
(function(){
  var GlobalConfig, gconf, path, Filter, toString$ = {}.toString;
  GlobalConfig = require('../../global-config');
  gconf = new GlobalConfig;
  path = require('path');
  module.exports = Filter = (function(){
    Filter.displayName = 'Filter';
    var prototype = Filter.prototype, constructor = Filter;
    function Filter(config){
      this.config = config;
      this.validate();
      this;
    }
    prototype.validate = function(){
      if (toString$.call(this.config).slice(8, -1) !== 'Object') {
        throw new Error("Config to filter must be an Object, was: " + this.config);
      }
    };
    prototype.filter = function(){
      var i$, ref$, len$, key, results$ = [];
      for (i$ = 0, len$ = (ref$ = this.filterPrefKeys).length; i$ < len$; ++i$) {
        key = ref$[i$];
        results$.push(this.filterOn(key));
      }
      return results$;
    };
    prototype.filterOn = function(name){
      var files, i$, ref$, len$, pref;
      files = this.configFor(name).files;
      for (i$ = 0, len$ = (ref$ = this.prefsFor(name)).length; i$ < len$; ++i$) {
        pref = ref$[i$];
        return this.filterPref(files, pref);
      }
    };
    prototype.filterPref = function(files, prefs){
      var i$, len$, file, j$, len1$, pref;
      if (toString$.call(prefs).slice(8, -1) !== 'Array') {
        prefs = [prefs];
      }
      for (i$ = 0, len$ = files.length; i$ < len$; ++i$) {
        file = files[i$];
        for (j$ = 0, len1$ = prefs.length; j$ < len1$; ++j$) {
          pref = prefs[j$];
          if (this.matches(file, pref)) {
            return file;
          }
        }
      }
    };
    prototype.filterOne = function(files, file, prefs){
      var sameFiles, bestFile;
      sameFiles = this.same(files, file);
      bestFile = this.filterPref(sameFiles, prefs);
      return files.filter(function(file){
        return file === bestFile || sameFiles.indexOf(file) === -1;
      });
    };
    prototype.same = function(files, file){
      var fname, this$ = this;
      fname = this.fileName(file);
      return files.filter(function(name){
        return this$.fileName(name) === fname;
      });
    };
    prototype.fileName = function(file){
      return path.basename(file, path.extname(file));
    };
    prototype.matches = function(file, pref){
      if (toString$.call(pref).slice(8, -1) !== 'String') {
        return false;
      }
      if (pref[0] !== '.') {
        pref = "." + pref;
      }
      return !!(path.extname(file) === pref);
    };
    prototype.configFor = function(name){
      return this.config[name];
    };
    prototype.prefsFor = function(name){
      return this.filterPrefs()[name];
    };
    prototype.filterPrefKeys = function(){
      return Object.keys(this.filterPrefs());
    };
    prototype.filterPrefs = function(){
      return this.prefs || (this.prefs = gconf.preferences());
    };
    return Filter;
  }());
}).call(this);
