// Generated by LiveScript 1.2.0
(function(){
  var FileLoader, JsonLoader, CompositeLoader, ConfigLoader, toString$ = {}.toString;
  FileLoader = require('adater/file-loader');
  JsonLoader = require('adater/json-loader');
  CompositeLoader = require('adater/composite-loader');
  module.exports = ConfigLoader = (function(){
    ConfigLoader.displayName = 'ConfigLoader';
    var prototype = ConfigLoader.prototype, constructor = ConfigLoader;
    function ConfigLoader(name, options){
      this.name = name;
      this.options = options != null
        ? options
        : {};
      this.loader = this.options.loader || 'composite';
      this.component = this.options.component || 'bower';
      this.path = this.options.path;
      this.validate();
    }
    prototype.validate = function(){
      if (toString$.call(this.type).slice(8, -1) !== 'String') {
        throw new Error("Type must be a String, was: " + this.type);
      }
    };
    prototype.load = function(){
      return this.normalize(this.adapted());
    };
    prototype.normalize = function(config){
      return this.normalizer(config).normalize();
    };
    prototype.normalizer = function(config){
      return new Normalizer(config, this.componentType);
    };
    prototype.adapted = function(){
      return this.adapter().adapt();
    };
    prototype.adapter = function(){
      return new this.selectedLoader()(this.name, this.path, this.options);
    };
    prototype.selectedLoader = function(){
      switch (this.type) {
      case 'file':
        return FileLoader;
      case 'json':
        return JsonLoader;
      case 'composite':
        return CompositeLoader;
      default:
        throw new Error("unknown Installer " + this.type);
      }
    };
    return ConfigLoader;
  }());
}).call(this);
