// Generated by LiveScript 1.2.0
(function(){
  var BaseConfigLoader, LocalConfigLoader;
  BaseConfigLoader = require('./base');
  module.exports = LocalConfigLoader = (function(superclass){
    var prototype = extend$((import$(LocalConfigLoader, superclass).displayName = 'LocalConfigLoader', LocalConfigLoader), superclass).prototype, constructor = LocalConfigLoader;
    function LocalConfigLoader(name, path){
      this.name = name;
      this.path = path;
      LocalConfigLoader.superclass.apply(this, arguments);
      this.validate();
      this;
    }
    return LocalConfigLoader;
  }(BaseConfigLoader));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
