// Generated by LiveScript 1.2.0
(function(){
  var BaseLoader, GlobalConfig, gconf, JsonConfigLoader, toString$ = {}.toString;
  BaseLoader = require('../base-loader');
  GlobalConfig = require('../../../../global-config');
  gconf = new GlobalConfig;
  module.exports = JsonConfigLoader = (function(superclass){
    var prototype = extend$((import$(JsonConfigLoader, superclass).displayName = 'JsonConfigLoader', JsonConfigLoader), superclass).prototype, constructor = JsonConfigLoader;
    function JsonConfigLoader(name, path, options){
      this.name = name;
      this.path = path;
      this.options = options != null
        ? options
        : {};
      this.path || (this.path = gconf.location('components.dir'));
      JsonConfigLoader.superclass.apply(this, arguments);
      this.validate();
      this;
    }
    prototype.validate = function(){
      if (toString$.call(this.path).slice(8, -1) !== 'String') {
        throw new Error("Path of config to load must be a String, was: " + this.path);
      }
      if (!this.exists(this.configFile())) {
        throw new Error("Components file " + this.configFile() + " does not exist");
      }
    };
    prototype.list = function(){
      return Object.keys(this.jsonConfig());
    };
    prototype.loadConfig = function(name){
      name || (name = this.name);
      if (!this.jsonConfig()[name]) {
        throw Error("No entry for " + name);
      }
      return this.jsonConfig()[name];
    };
    prototype.hasConfig = function(name){
      var e;
      name || (name = this.name);
      try {
        return !!this.loadConfig(name);
      } catch (e$) {
        e = e$;
        return false;
      }
    };
    prototype.jsonConfig = function(){
      return this._jsonConf || (this._jsonConf = this.json(this.configFile()));
    };
    prototype.configFile = function(){
      return [this.path, "index.json"].join('/');
    };
    return JsonConfigLoader;
  }(BaseLoader));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
